pipeline {
  agent any

  options {
    timestamps()
  }

  environment {
    REPORT_FILE = ''
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Verify k6') {
      steps {
        sh 'k6 version'
      }
    }

    stage('Run k6 Test') {
      steps {
        sh '''
          set -e
          echo "Running k6 load test..."
          k6 run script.js
        '''
      }
    }

    stage('Collect Report') {
      steps {
        script {
          def report = sh(
            script: "ls -1 report_*.html 2>/dev/null | sort | tail -n 1 || true",
            returnStdout: true
          ).trim()

          if (!report) {
            error "No HTML report generated by k6"
          }

          env.REPORT_FILE = report
          echo "Found report: ${env.REPORT_FILE}"

          archiveArtifacts artifacts: env.REPORT_FILE, fingerprint: true
        }
      }
    }
  }

  post {

    success {
      script {
        def reportLink = "${env.BUILD_URL}artifact/${env.REPORT_FILE}"

        slackSend(
          channel: "#all-poc-k6",
          message: """✅ *k6 POC PASSED*
• Job: ${env.JOB_NAME}
• Build: ${env.BUILD_NUMBER}
• Download HTML Report:
${reportLink}

(Open in browser for full colors & charts)
"""
        )
      }
    }

    failure {
      slackSend(
        channel: "#all-poc-k6",
        message: """❌ *k6 POC FAILED*
• Job: ${env.JOB_NAME}
• Build: ${env.BUILD_NUMBER}
• Logs: ${env.BUILD_URL}
"""
      )
    }
  }
}
