pipeline {
  agent any

  options {
    timestamps()
    skipDefaultCheckout(true)
  }

  environment {
    REPORT_FILE = ""
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Verify k6') {
      steps {
        sh 'k6 version'
      }
    }

    stage('Run k6 Test') {
      steps {
        sh '''
          set -e
          echo "Running k6 load test..."
          k6 run script.js
        '''
      }
    }

    stage('Collect Report') {
      steps {
        script {
          // Get latest generated HTML report
          def reportFile = sh(
            script: "ls -1 report_*.html 2>/dev/null | sort | tail -n 1",
            returnStdout: true
          ).trim()

          if (!reportFile) {
            error "No HTML report generated by k6"
          }

          echo "Found report: ${reportFile}"

          // Rename report with build number (IMPORTANT)
          def finalReport = "k6_report_build_${env.BUILD_NUMBER}.html"

          sh "mv ${reportFile} ${finalReport}"

          // Save for later stages
          env.REPORT_FILE = finalReport

          // Archive in Jenkins
          archiveArtifacts artifacts: finalReport, fingerprint: true
        }
      }
    }
  }

  post {

    success {
      script {
        def reportLink = "${env.BUILD_URL}artifact/${env.REPORT_FILE}"

        slackSend(
          channel: "#all-poc-k6",
          message: """✅ *k6 POC PASSED*
• Job: ${env.JOB_NAME}
• Build: ${env.BUILD_NUMBER}
• 📊 Report: ${reportLink}

⬆️ Click the link to open the full HTML report with colors & charts.
"""
        )
      }
    }

    failure {
      slackSend(
        channel: "#all-poc-k6",
        message: """❌ *k6 POC FAILED*
• Job: ${env.JOB_NAME}
• Build: ${env.BUILD_NUMBER}
• Logs: ${env.BUILD_URL}
"""
      )
    }
  }
}
